[project]
name = "immo-finder"
version = "0.1.0"
description = "Scrapper to find immo"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "html5lib>=1.1",
    "selenium-stealth>=1.0.6",
    "six>=1.17.0",
    "undetected-chromedriver>=3.5.5",
]
